# Copyright (c) Zensical LLC <https://zensical.org>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Zensical Documentation
site_url: https://zensical.org/docs/
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes â€“ searchable, customizable, in 60+ languages, for all devices

# Repository
repo_name: zensical/zensical
repo_url: https://github.com/zensical/zensical
edit_uri: https://github.com/zensical/docs/edit/master/docs/

# Copyright
copyright: Copyright &copy; 2025 Zensical LLC

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: lucide/sun-moon
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: lucide/sun
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: lucide/moon-star
        name: Switch to system preference
  favicon: assets/zensical.png
  logo: assets/zensical.svg
  icon:
    tag:
      default: lucide/hash

extra_css:
  - assets/stylesheets/extra.css

# Plugins
plugins:
  - search
  - tags

# Additional configuration
extra:
  homepage: https://zensical.org
  scope: /
  annotate:
    json: [.s2]
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zensical
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/hqXRNq9CjT
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/zensical/
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/zensical.org
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@zensical
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/zensical
  tags:
    default: default

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - zensical.extensions.preview:
      targets:
        include:
          - customization.md
          - setup/extensions/*
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:zensical.extensions.emoji.to_svg
      emoji_index: !!python/name:zensical.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: zensical
      repo: zensical
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: https://zensical.org
  - Get started:
    - Get started: get-started.md
    - Create your site: create-your-site.md
    - Publish your site: publish-your-site.md
    - Customization: customization.md
    - How to upgrade: upgrade.md
    - Browser support: browser-support.md
    - License: license.md
  - Usage:
    - Command line: usage/cli.md
    - New project: usage/new.md
    - Preview: usage/preview.md
    - Build: usage/build.md
  - Setup:
    - Basics: setup/basics.md
    - Colors: setup/colors.md
    - Fonts: setup/fonts.md
    - Language: setup/language.md
    - Logo and icons: setup/logo-and-icons.md
    - Data privacy: setup/data-privacy.md
    - Navigation: setup/navigation.md
    - Site search: setup/search.md
    - Site analytics: setup/analytics.md
    - Social cards: setup/social-cards.md
    - Tags: setup/tags.md
    - Header: setup/header.md
    - Footer: setup/footer.md
    - Repository: setup/repository.md
    - Comment system: setup/comment-system.md
    - Offline usage: setup/offline.md
    - Extensions:
      - setup/extensions/index.md
      - Markdown: setup/extensions/python-markdown.md
      - Markdown Extensions: setup/extensions/python-markdown-extensions.md
      - mkdocstrings: setup/extensions/mkdocstrings.md
  - Authoring:
    - Markdown: authoring/markdown.md
    - Front matter: authoring/frontmatter.md
    - Admonitions: authoring/admonitions.md
    - Buttons: authoring/buttons.md
    - Code blocks: authoring/code-blocks.md
    - Content tabs: authoring/content-tabs.md
    - Data tables: authoring/data-tables.md
    - Diagrams: authoring/diagrams.md
    - Footnotes: authoring/footnotes.md
    - Formatting: authoring/formatting.md
    - Grids: authoring/grids.md
    - Icons, Emojis: authoring/icons-emojis.md
    - Images: authoring/images.md
    - Lists: authoring/lists.md
    - Math: authoring/math.md
    - Tooltips: authoring/tooltips.md
  - Community:
    - Get involved: community/get-involved.md
    - How we work: community/how-we-work.md
    - Contribute:
      - community/contribute/index.md
      - Bug reports: community/contribute/report-a-bug.md
      - Documentation: community/contribute/report-a-docs-issue.md
      - Change requests: community/contribute/request-a-change.md
      - Code of conduct: community/contribute/code-of-conduct.md
    - Guides:
      - Reproductions: community/guides/create-a-reproduction.md

